name: Workflow for Codecov example-python

on:
  push:
    branches:
    - "main"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Ruby latest
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 'head'
      - name: Install dependencies
        run: bundle install
      - name: Run tests and collect coverage
        run: bundle exec rake
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          url: ${{ secrets.CODECOV_URL }}
          token: ${{ secrets.CODECOV_TOKEN }}
